# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_APP_VALUE_LEN "1")
set(CPACK_BUILD_SOURCE_DIRS "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid;E:/yjw/Graphics/Learning/Project/Renderer/Alkaid")
set(CPACK_CMAKE_GENERATOR "Visual Studio 17 2022")
set(CPACK_COMPONENTS_ALL "library;dev;tools")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_DEV_DEPENDS "library")
set(CPACK_COMPONENT_DEV_DESCRIPTION "Additional resources for development (header files and documentation).")
set(CPACK_COMPONENT_DEV_DISABLED "TRUE")
set(CPACK_COMPONENT_DEV_DISPLAY_NAME "Development")
set(CPACK_COMPONENT_DEV_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_DEV_HIDDEN "FALSE")
set(CPACK_COMPONENT_DEV_REQUIRED "FALSE")
set(CPACK_COMPONENT_GLLOADTESTAPPS_DISABLED "TRUE")
set(CPACK_COMPONENT_GLLOADTESTAPPS_DISPLAY_NAME "OpenGL Test Applications")
set(CPACK_COMPONENT_GLLOADTESTAPPS_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_GLLOADTESTAPPS_GROUP "LoadTestApps")
set(CPACK_COMPONENT_GLLOADTESTAPPS_HIDDEN "FALSE")
set(CPACK_COMPONENT_GLLOADTESTAPPS_REQUIRED "FALSE")
set(CPACK_COMPONENT_GROUP_LOADTESTAPPS_BOLD_TITLE "FALSE")
set(CPACK_COMPONENT_GROUP_LOADTESTAPPS_DISPLAY_NAME "Load Test Applications")
set(CPACK_COMPONENT_GROUP_LOADTESTAPPS_EXPANDED "FALSE")
set(CPACK_COMPONENT_JNI_DEPENDS "library")
set(CPACK_COMPONENT_JNI_DESCRIPTION "Java wrapper and native interface for KTX library.")
set(CPACK_COMPONENT_JNI_DISABLED "TRUE")
set(CPACK_COMPONENT_JNI_DISPLAY_NAME "Java wrapper")
set(CPACK_COMPONENT_JNI_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_JNI_HIDDEN "FALSE")
set(CPACK_COMPONENT_JNI_REQUIRED "FALSE")
set(CPACK_COMPONENT_LIBRARY_DESCRIPTION "Main KTX library.")
set(CPACK_COMPONENT_LIBRARY_DISABLED "FALSE")
set(CPACK_COMPONENT_LIBRARY_DISPLAY_NAME "Library")
set(CPACK_COMPONENT_LIBRARY_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_LIBRARY_HIDDEN "FALSE")
set(CPACK_COMPONENT_LIBRARY_REQUIRED "TRUE")
set(CPACK_COMPONENT_TOOLS_DEPENDS "library")
set(CPACK_COMPONENT_TOOLS_DESCRIPTION "Command line tools for creating, converting and inspecting KTX files.")
set(CPACK_COMPONENT_TOOLS_DISABLED "FALSE")
set(CPACK_COMPONENT_TOOLS_DISPLAY_NAME "Command line tools")
set(CPACK_COMPONENT_TOOLS_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_TOOLS_HIDDEN "FALSE")
set(CPACK_COMPONENT_TOOLS_REQUIRED "FALSE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_COMPONENT_VKLOADTESTAPP_DISABLED "TRUE")
set(CPACK_COMPONENT_VKLOADTESTAPP_DISPLAY_NAME "Vulkan Test Application")
set(CPACK_COMPONENT_VKLOADTESTAPP_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_VKLOADTESTAPP_GROUP "LoadTestApps")
set(CPACK_COMPONENT_VKLOADTESTAPP_HIDDEN "FALSE")
set(CPACK_COMPONENT_VKLOADTESTAPP_REQUIRED "FALSE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "E:/yjw/CS/Plugin/CMake/share/cmake-3.26/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Alkaid built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "NSIS")
set(CPACK_INSTALL_CMAKE_PROJECTS "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid;Alkaid;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/Project")
set(CPACK_MODULE_PATH "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/external/ktx/cmake/modules/")
set(CPACK_NSIS_BRANDING_TEXT "KTX for Windows")
set(CPACK_NSIS_CONTACT "khronos@callow.im")
set(CPACK_NSIS_DISPLAY_NAME "KTX-Software")
set(CPACK_NSIS_INSTALLED_ICON_NAME "uninstall.exe")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_MANIFEST_DPI_AWARE "ON")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_MUI_ICON "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/external/ktx/icons/win/ktx_app.ico")
set(CPACK_NSIS_MUI_UNIICON "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/external/ktx/icons/win/ktx_app.ico")
set(CPACK_NSIS_PACKAGE_NAME "KTX-Software")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "https://github.khronos.org/KTX-Software")
set(CPACK_OUTPUT_CONFIG_FILE "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/CPackConfig.cmake")
set(CPACK_PACKAGE_CHECKSUM "SHA1")
set(CPACK_PACKAGE_CONTACT "khronos@callow.im")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "E:/yjw/CS/Plugin/CMake/share/cmake-3.26/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Alkaid built using CMake")
set(CPACK_PACKAGE_FILE_NAME "Alkaid-0.0.0-noversion-Windows-x64")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.khronos.org/KTX-Software")
set(CPACK_PACKAGE_ICON "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/external/ktx/icons/win\\ktx_logo_200_bmp3.bmp")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "KTX-Software")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "KTX-Software")
set(CPACK_PACKAGE_NAME "KTX-Software")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Khronos Group")
set(CPACK_PACKAGE_VERSION "0.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_RESOURCE_FILE_LICENSE "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/external/ktx/cmake/License.rtf")
set(CPACK_RESOURCE_FILE_README "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/external/ktx/cmake/ReadMe.rtf")
set(CPACK_RESOURCE_FILE_WELCOME "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/external/ktx/cmake/Welcome.rtf")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/CPackSourceConfig.cmake")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "E:/yjw/Graphics/Learning/Project/Renderer/Alkaid/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
